### ISSUE TITLE
Need proper exception mapper for BeanValidationException

### ISSUE THREAD

**Issue by anandsomani** [proofpoint/platform#190]
Introduced in 0.69 => Previously constraint exceptions were returned as a list of strings
But with this change we are just returning the exception message as a string so, instead of

["id[0] is not correct format", "id[5]  is not correct format"]

We get
"[id[0] is not correct format, id[5] is not correct format]"

Couple of options add a BeanValidationExceptionMapper or make the ParsingException more generic by introducing another method that is used by the ParsingExceptionMapper to get the actual message and this method could just return object and the overriding exceptions can have their own implementation

**Comment by johngmyers** [comment]
WONTFIX
