### ISSUE TITLE
Failure to parse @QueryParam Results In 404

### ISSUE THREAD

**Issue by gwittel** [proofpoint/platform#379]
If you have an API with a ```@QueryParam``` annotated parameter, and someone submits a request with the parameter that Jersey can't parse (e.g. string for int), it results in a 404 not found instead of a 400 bad request.  This is a highly misleading response.

Its a simple fix via implementing an ```ExceptionMapper```.

If this sounds useful I can go ahead and create the PR (I assume this would get dropped into the jaxrs module)

**Comment by johngmyers** [comment]
Go ahead.

**Comment by gwittel** [comment]
Merged in 973f9d1a27072bac5e0256ad87a33348c697f0e3
