### ISSUE TITLE
Lock Contention In HttpServiceBalancerImpl

### ISSUE THREAD

**Issue by gwittel** [proofpoint/platform#394]
In situations with high request volumes to a small set of URIs, we observed lock contention in blocks that synchronize on `concurrentAttempts` within the `HttpServiceBalancerImpl`.  In particular, we see blocking in two places:
1.  `HttpServiceAttemptImpl(Set<URI> attempted)`
2.  `HttpServiceAttemptImpl#decrementConcurrency`

The locking system could use improvements given its a single lock across all URIs.

**Comment by johngmyers** [comment]
Please file this in the internal tracking system if you still want to move this forward.
