### ISSUE TITLE
Lock Contention In UUID Generation Due To SecureRandom API

### ISSUE THREAD

**Issue by gwittel** [proofpoint/platform#397]
We've observed UUID generation as needed by the event system being slowed due to many threads wanting random numbers at once.

Underneath, the Java UUID class uses `SecureRandom#nextBytes()` to get the randomized portion of the UUID.  There are two points of possible contention:
-  `SecureRandom` is synchronized on `nextBytes()` (not in the Javadoc but its in the OpenJDK source).  Lots of threads using `SecureRandom` can cause contention.   This can be mitigated by a per thread `SecureRandom` instance, but requires us to write a `UUID.randomUUID()` replacement.  
- On Linux, `SecureRandom` by default relies on `/dev/random` being able to supply data fast enough.  While a per thread `SecureRandom` will resolve contention on `nextBytes()`, if `/dev/random` is blocking, this won't help.  Options:
  - Configure JVM to use different RNG (like `/dev/urandom`).  This is a bad idea in Java 7 as its JVM wide.  No way.  In Java 8 you can configure individual `SecureRandom` instances (see [JEPS-123](http://openjdk.java.net/jeps/123))
  - Use `ThreadLocalRandom` instead of `SecureRandom`.  The implications of doing this are unclear.  It may be application dependent so its probably best to not do this.

I suggest we handle writing our own `UUID.randomUUID()` replacement; but defer on the PRNG configuration unless/until Java 8 is required by Platform.

**Comment by johngmyers** [comment]
`/dev/urandom` is not blocking. `/dev/random` is.

**Comment by gwittel** [comment]
Doh.  I flipped them.  JDK does rely on ```/dev/random``` by default.  I will update the original request.

**Comment by johngmyers** [comment]
Current plan is to wait until we drop support for Java 7.

**Comment by johngmyers** [comment]
The event system and the HttpServer's `TraceTokenFilter` now use `ThreadLocal` instances of `SecureRandom`. Nothing practical can be done with the TLS implementation in JSSE.
