### ISSUE TITLE
Implement and expose version number of service

### ISSUE THREAD

**Issue by rajatjindal83** [proofpoint/platform#408]
It will be great, if we can have '/status' end point implemented for all the services which can return back some basic information about the server status. Atleast the version number.

By the time RPM is built, we already have snapshot version number of the server jar file. We can probably store this in version file while creating the RPM and expose it using the end point.

Even better if we can announce the version number to discovery automatically. [Not a must required feature though]

This way, when we run our tests, we can easily capture and document the version of service tests were ran against.

**Comment by johngmyers** [comment]
https://stackoverflow.com/questions/2712970/how-to-get-maven-artifact-version-at-runtime
suggests some approaches.

**Comment by johngmyers** [comment]
https://stackoverflow.com/questions/20870046/version-information-for-java-library-accessible-at-runtime?lq=1

**Comment by johngmyers** [comment]
Seems to me to make more sense to send version number(s) to Pulse.

**Comment by ssindkar** [comment]
A library should expose an API with a version string
A web service needs to have a standard REST interface to query its version information (https://webauth.hpconnected.com/oauth/about - result listed below,) in JSON format (comparable to the xml below)

<about>
<serviceName>urn:hp:cloud:eprint:papi:services:puma</serviceName>
<apiVersion>2.0</apiVersion>
<serviceRevision>2.0.68</serviceRevision>
<serviceBuildDate>2014-12-28T10:02:11.000Z</serviceBuildDate>
<sourceRevision>3375</sourceRevision>
<stackName>DEV MACHINE</stackName>
<databaseSchema>N/A</databaseSchema>
<artifact>com.hp.swp:oauth-web:15.02.1.0</artifact>
</about>

Chrz,

GN
C: 408.627.4234
GTalk/Hangouts: gadinaveh@gmail.com<mailto:gadinaveh@gmail.com>
proofpoint Chat: Gadi Naveh

Sent from somewhere…else

**Comment by alecswan** [comment]
+1 for REST service. Would like to also include specific Git commit & branch information.
In fact we already expose such a service in several projects, such as social and event indexer, and are planning to add it to event collectors. Would be nice if platform, i.e. rest-server, had this built in. This is what the output of our REST service looks like today (it's easy to add more information):
{
    "git.commit.id": "0d90fd37351e564b2665ef0cb49cfb2c25a89d57",
    "git.build.time": "21.01.2015 @ 18:41:51 PST",
    "git.commit.time": "21.01.2015 @ 18:41:34 PST",
    "git.branch": "origin/master",
    "git.commit.id.abbrev": "0d90fd3",
    "git.commit.id.describe": "jenkins-event-indexer-release-3-1-g0d90fd3"
}

**Comment by johngmyers** [comment]
Exposing an API/resource like this invites consumers to handle the data inconsistently or even break if the version string is not what they expect. This is the sort of internal information that should not be exposed over the public service port.

Done right, sending to KairosDB would allow an easy query of which deployed users of a library require remediation, without any effort on the part of the users (other than to get KairosDB reporting enabled at all). And reported metrics are usually made available under the /admin/jmx/mbean resource on the admin port.

**Comment by ssindkar** [comment]
This will not be publicly exposed but used internally. I am looking for this capability from the platform in the form of api.


Chrz,

GN

C: 408.627.4234<tel:408.627.4234>
GTalk: gadinaveh@gmail.com<mailto:gadinaveh@gmail.com>
Chat: Gadi Naveh (proofpoint chat)

Sent from somewhere…else

**Comment by rajatjindal83** [comment]
I second that. This is something which should can start with internal use only but can be extended to define version when querying dependency from discovery. 

It is something we need badly for our test infrastructure to tie test results with deterministic env by capturing version number from actual service rather than going to pulse to query this.

As of today, we do ssh and then rpm -qa which is not scalable and not even an option for prod.

Another hook that we can easily implement using this to have validations on version configured in cmdb vs actual version deployed, which i believe is something useful for prod validations too.

**Comment by ssindkar** [comment]
Right on – these are the other uses for this


-          Version validation after deploy

-          Inventory

-          Health checks

-          And so on.


Chrz,

GN
C: 408.627.4234
GTalk/Hangouts: gadinaveh@gmail.com<mailto:gadinaveh@gmail.com>
proofpoint Chat: Gadi Naveh

Sent from somewhere…else

**Comment by alecswan** [comment]
For QA validation you definitely want to display information from Git and Jenkins.

**Comment by johngmyers** [comment]
QA validation and health checks are reasonably done with the admin port. There's no need for them to use the public service port.

**Comment by alecswan** [comment]
I am not aware of any service on the admin port that exposes this information today.

**Comment by ssindkar** [comment]
This is up to the teams that own the services to decide. The team need to have the option to define the ports they want to work with – they own the service, it is there decision.

We need to turn this into a more structured requirement collection process, not over email but rather through the wiki with comments and full details of the requirements. I will ask Anand S to follow.


Chrz,

GN
C: 408.627.4234
GTalk/Hangouts: gadinaveh@gmail.com<mailto:gadinaveh@gmail.com>
proofpoint Chat: Gadi Naveh

Sent from somewhere…else

**Comment by johngmyers** [comment]
This is a public GitHub issue.
The proposal is to report the information to KairosDB, which also makes it available via JMX and the admin port.

**Comment by johngmyers** [comment]
Moved to internal tracking system
