### ISSUE TITLE
Support ignoring unused properties

### ISSUE THREAD

**Issue by gdasbach** [proofpoint/platform#668]
The requireExplicitBindings method in Bootstrap states this in the comments:

> Set whether properties in configuration files must be consumed by configuration.

Yet, setting this to "false" still causes validation errors if there are unused configuration properties.

**Comment by gdasbach** [comment]
Added a fix for this in PR https://github.com/proofpoint/platform/pull/669

**Comment by johngmyers** [comment]
#674 fixes the documentation.

**Comment by johngmyers** [comment]
The requirement to consume all properties in configuration files is to catch typoed configuration property names in configuration files. It is unlikely we would support disabling this check.

**Comment by gdasbach** [comment]
Completely understand if the documentation on that method is incorrect, and not re-using that property to support ignoring unused configuration.  However, a separate property on Bootstrap to ignore unused properties (defaulting to false), would still force the check by default but allow the app developer to disable it if makes sense for their use-case.  Typical examples of how this can bite us:

1. In development (when switching between branches with local configuration)
2. In rollback scenarios where a rollback will fail because the config files contain settings that weren't used by the previous version, delaying the rollback while all the config files are reset

**Comment by johngmyers** [comment]
Please file this in the internal tracking system if you still want to move this forward.
