### ISSUE TITLE
Support local configuration for development

### ISSUE THREAD

**Issue by gdasbach** [proofpoint/platform#670]
A common issue I've run into is working on development of a platform application and requiring a set of local configuration overrides for development.  Ideally I don't want to have to edit the config.properties file to hold my local overrides (and accidentally check something in or deal with merge conflicts when stashing).  While properties can be overloaded via System Properties, this can get cumbersome with a lot of local overrides.  Ideally, I should be able to have a local.properties file (optionally), that overrides config settings, but something I should never have to check into my repo.

**Comment by johngmyers** [comment]
Please file this in the internal ticket system if you still want to move this forward.
