### ISSUE TITLE
Upgrade ch.qos.logback:logback-core 

### ISSUE THREAD

**Issue by apismensky** [proofpoint/platform#935]
We have an issue, related to the outdated version of the ch.qos.logback:logback-core, that platform is using. 
<dep.logback.version>1.2.11</dep.logback.version>
com.proofpoint.log.Logging is using 'lock' variable in 
```
 private void flush()
        {
            try {
                lock.lock();
                try {
                    getOutputStream().flush();
                }
                finally {
                    lock.unlock();
                }
            }
            catch (IOException e) {
                started = false;
                addStatus(new ErrorStatus("IO failure in appender", this, e));
            }
        }
```
and lock is declared in logback-core, version in 1.2.11: 
`ch.qos.logback.core.OutputStreamAppender#lock` 
In the latest version of the logback-core it is renamed to `streamWriteLock`, see: 
https://github.com/qos-ch/logback/blob/master/logback-core/src/main/java/ch/qos/logback/core/OutputStreamAppender.java#L47

And code that has a dependency on the latest platform and latest logback-core fails with the Runtime error: 

java.lang.NoSuchFieldError: lock at com.proofpoint.log.Logging$FlushingFileAppender.flush(Logging.java:477) at com.proofpoint.log.Logging$FlushingFileAppender.subAppend(Logging.java:469) at ch.qos.logback.core.OutputStreamAppender.append(OutputStreamAppender.java:102) at ch.qos.logback.core.UnsynchronizedAppenderBase.doAppend(UnsynchronizedAppenderBase.java:85) at ch.qos.logback.core.spi.AppenderAttachableImpl.appendLoopOnAppenders(AppenderAttachableImpl.java:51) at ch.qos.logback.core.AsyncAppenderBase$Worker.run(AsyncAppenderBase.java:302)

We have temporarily downgraded logback-core version in the project (1.4.7), but it would be great to keep the version of logback-core in the platform up-to-date.

**Comment by johngmyers** [comment]
Done
